# This file defines your local development services
version: '3.8'
services:
  # This is your PostgreSQL database
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword #export DATABASE_URL="postgresql://postgres:Reds0404!@10.162.28.53:5432/eventecho
      - POSTGRES_DB=eventecho
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    # This creates a persistent "volume" so your data
    # doesn't get erased every time you restart the container
